#
# Module manifest for module 'PSRegedit'
#
# Generated by: Jens Schmitz
#
# DISCLAIMER: This module is provided "as is", without warranty of any kind.
# The author(s) accept no liability for any damage, data loss, or system
# instability caused by modifications to the Windows Registry. Always back up
# your registry before making changes. Use at your own risk.
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'psregedit.dll'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Core')

# ID used to uniquely identify this module
GUID = 'c4f2b8d6-7e9a-4b3c-8f1e-2d5a7c9e0b3f'

# Author of this module
Author = 'https://github.com/xRushG'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = '(c) https://github.com/xRushG. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell binary module for reading and writing the Windows Registry using the CSharpLibraSuite.WinRegistry library.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @('Requires-Runtime.ps1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @(
    'Get-RegSubKeyNames',
    'Get-RegValue',
    'Get-RegEntry',
    'Get-RegEntries',
    'Set-RegValue',
    'New-RegKey',
    'Remove-RegValue',
    'Remove-RegTree'
)

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @('New-RegValue')

# Private data to pass to the module specified in RootModule/ModuleToProcess.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('registry', 'windows', 'winreg', 'regedit')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
